name 'hfsplus'
maintainer 'James Cuzella'
maintainer_email 'james.cuzella@lyraphase.com'
license 'gplv3'
description 'Installs/Configures hfsplus'
long_description 'Installs/Configures hfsplus'
version '0.1.0'
